import React from "react";
import { Box } from "@chakra-ui/react";
import TestForm from "../components/login/testForm";
import Head from "next/head";

const login = () => {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TestForm />
    </Box>
  );
};

export default login;
